# build_spa.py — gzip-embed pipeline (firmware spec §10.1 / DEC-002, #59).
#
# PlatformIO extra_script (pre): regenerates src/esp32/spa_gz.h from
# web/index.html on every esp32/esp32_sim build, so the served SPA can never go
# stale against the source — there is no manual build step to forget. The header
# is generated, gitignored, and write-on-change (deterministic gzip, mtime=0) so
# an untouched SPA never dirties the incremental build.
#
# HARD GATE: the gzipped bundle must stay under SPA_GZ_BUDGET (spec: "under
# ~50 KB gzipped"). Overrunning it fails the build loudly rather than silently
# eating the flash headroom.

Import("env")  # noqa: F821 — provided by the SCons/PlatformIO runtime

import gzip
import hashlib
import io
from pathlib import Path

SPA_GZ_BUDGET = 50 * 1024

root = Path(env["PROJECT_DIR"])  # noqa: F821
src = root / "web" / "index.html"
out = root / "src" / "esp32" / "spa_gz.h"

html = src.read_bytes()

# SIM build only (TINKLE_SIM): Wokwi's net.forward proxy opens a fresh socket per
# SPA poll, and the device's small TCP pool exhausts in ~20s at the production 1 Hz
# cadence (the SPA then can't reconnect though WiFi/sim stay up). Real hardware talks
# to the phone directly — keep-alive reuse, more sockets — so production keeps the
# snappy poll. Slow the poll for the sim build only, by substituting the named knob.
# Detect from the resolved build_flags (CPPDEFINES isn't merged yet at pre-script time).
_flags = str(env.GetProjectOption("build_flags", "")) + " " + env.subst("$BUILD_FLAGS")  # noqa: F821
if "TINKLE_SIM" in _flags:
    _needle = b"const POLL_ACTIVE_MS = 1000, POLL_IDLE_MS = 2000;"
    _repl = b"const POLL_ACTIVE_MS = 5000, POLL_IDLE_MS = 8000;"
    _n = html.count(_needle)
    if _n != 1:
        raise SystemExit(
            "build_spa: TINKLE_SIM poll knob matched %d times (expected 1) — "
            "web/index.html changed; update the marker in tools/build_spa.py." % _n
        )
    html = html.replace(_needle, _repl)
    print("build_spa: TINKLE_SIM -> SPA poll slowed to 5s/8s (Wokwi net.forward socket churn)")

# mtime=0 => byte-identical output for identical input (write-on-change works).
buf = io.BytesIO()
with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
    gz.write(html)
blob = buf.getvalue()

if len(blob) > SPA_GZ_BUDGET:
    raise SystemExit(
        "build_spa: gzipped SPA is %d bytes — over the %d-byte budget (§10.1). "
        "Trim web/index.html." % (len(blob), SPA_GZ_BUDGET)
    )

etag = hashlib.sha256(blob).hexdigest()[:8]

lines = [
    "// AUTO-GENERATED by tools/build_spa.py from web/index.html — DO NOT EDIT.",
    "// %d bytes raw -> %d bytes gzipped (budget %d). ETag %s." % (len(html), len(blob), SPA_GZ_BUDGET, etag),
    "#pragma once",
    "#include <stdint.h>",
    "#include <stddef.h>",
    "#include <pgmspace.h>",
    "",
    "constexpr size_t SPA_GZ_LEN = %d;" % len(blob),
    'constexpr char SPA_ETAG[] = "\\"%s\\"";' % etag,
    "const uint8_t SPA_GZ[] PROGMEM = {",
]
for i in range(0, len(blob), 16):
    lines.append("    " + "".join("0x%02x," % b for b in blob[i:i + 16]))
lines.append("};")
header = "\n".join(lines) + "\n"

if not out.exists() or out.read_text() != header:
    out.write_text(header)
    print("build_spa: %s -> %s (%d gz bytes, etag %s)" % (src.name, out.name, len(blob), etag))
